In [4]:
import numpy as np

In [5]:
myArr=[1,2,3,4,5,6]
Arr=np.array(myArr)

In [6]:
type(myArr)

list

In [7]:
type(Arr)

numpy.ndarray

In [8]:
Arr

array([1, 2, 3, 4, 5, 6])

In [9]:
Arr.shape

(6,)

In [12]:
A1=[1,2,3,4,5]
A2=[6,7,8,9,10]
A3=[11,12,13,14,15]
ARR=np.array([A1,A2,A3])

In [13]:
ARR

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [16]:
type(ARR)


numpy.ndarray

In [17]:
ARR.shape

(3, 5)

In [22]:
ARR.reshape(5,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [23]:
ARR.reshape(5,4)

ValueError: cannot reshape array of size 15 into shape (5,4)

In [24]:
ARR.shape

(3, 5)

In [25]:
ARR.reshape(1,15)#1D

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]])

In [28]:
ARR[0][2]

3

In [29]:
ARR[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [30]:
ARR[0:1]

array([[1, 2, 3, 4, 5]])

In [31]:
ARR[1:,3:]

array([[ 9, 10],
       [14, 15]])

In [33]:
ARRAY=np.arange(0,9)

In [34]:
ARRAY

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [37]:
EquallySpacedArray=np.linspace(1,10,100)

In [38]:
EquallySpacedArray

array([ 1.        ,  1.09090909,  1.18181818,  1.27272727,  1.36363636,
        1.45454545,  1.54545455,  1.63636364,  1.72727273,  1.81818182,
        1.90909091,  2.        ,  2.09090909,  2.18181818,  2.27272727,
        2.36363636,  2.45454545,  2.54545455,  2.63636364,  2.72727273,
        2.81818182,  2.90909091,  3.        ,  3.09090909,  3.18181818,
        3.27272727,  3.36363636,  3.45454545,  3.54545455,  3.63636364,
        3.72727273,  3.81818182,  3.90909091,  4.        ,  4.09090909,
        4.18181818,  4.27272727,  4.36363636,  4.45454545,  4.54545455,
        4.63636364,  4.72727273,  4.81818182,  4.90909091,  5.        ,
        5.09090909,  5.18181818,  5.27272727,  5.36363636,  5.45454545,
        5.54545455,  5.63636364,  5.72727273,  5.81818182,  5.90909091,
        6.        ,  6.09090909,  6.18181818,  6.27272727,  6.36363636,
        6.45454545,  6.54545455,  6.63636364,  6.72727273,  6.81818182,
        6.90909091,  7.        ,  7.09090909,  7.18181818,  7.27

In [39]:
#copy function and broadcasting
ARRAY[3:]=100
ARRAY

array([  0,   1,   2, 100, 100, 100, 100, 100, 100])

In [40]:
ARRAY1=ARRAY.copy()
ARRAY

array([  0,   1,   2, 100, 100, 100, 100, 100, 100])

In [41]:
ARRAY1[3:]=500
ARRAY1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500])

In [42]:
ARRAY

array([  0,   1,   2, 100, 100, 100, 100, 100, 100])

In [43]:
ARR%20

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]], dtype=int32)

In [44]:
ARR/20

array([[0.05, 0.1 , 0.15, 0.2 , 0.25],
       [0.3 , 0.35, 0.4 , 0.45, 0.5 ],
       [0.55, 0.6 , 0.65, 0.7 , 0.75]])

In [45]:
ARR*100

array([[ 100,  200,  300,  400,  500],
       [ 600,  700,  800,  900, 1000],
       [1100, 1200, 1300, 1400, 1500]])