In [3]:
import numpy as np

In [4]:
arr=np.arange(0,11)

In [5]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[8]

8

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[:5]

array([0, 1, 2, 3, 4])

In [10]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [11]:
#numpy array can broadcast
arr[0:5]=100
#not possible in normal python list 

In [12]:
arr=np.arange(0,11)

In [13]:
slice_of_arr=arr[0:5]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
slice_of_arr[:]=99
slice_of_arr
#slice of array u assiginging 99, original arrray is also affected

array([99, 99, 99, 99, 99])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [18]:
arr_copy=arr.copy()
arr_copy[:]=100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [19]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [21]:
arr_2d = np.array([[2,4,3],[12,34,56],[226,799,3],[12,3455,34]])
arr_2d

array([[   2,    4,    3],
       [  12,   34,   56],
       [ 226,  799,    3],
       [  12, 3455,   34]])

In [22]:
arr_2d.shape

(4, 3)

In [23]:
arr_2d[0]

array([2, 4, 3])

In [24]:
arr_2d[0][1]

4

In [25]:
arr_2d[0,2]

3

In [26]:
arr_2d[:2]

array([[ 2,  4,  3],
       [12, 34, 56]])

In [39]:
arr_2d[:1][2:]

array([], shape=(0, 3), dtype=int32)

In [40]:
arr_2d[:2,1:]

array([[ 4,  3],
       [34, 56]])

In [41]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [42]:
arr>4#numpy array of boolean vals

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True])

In [43]:
bool_arr=arr>50

In [44]:
bool_arr

array([ True,  True,  True,  True,  True, False, False, False, False,
       False, False])

In [45]:
arr[bool_arr]

array([99, 99, 99, 99, 99])

In [48]:
arr[arr>7]

array([99, 99, 99, 99, 99,  8,  9, 10])

In [49]:
arr=np.arange(0,10)

In [50]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [51]:
arr+5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [56]:
arr+arr
arr/arr


C:\Users\kunal\AppData\Local\Temp\ipykernel_32764\172818355.py:2: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
arr%arr

C:\Users\kunal\AppData\Local\Temp\ipykernel_32764\2578260503.py:1: RuntimeWarning: divide by zero encountered in remainder
  arr%arr


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [55]:
arr/arr

C:\Users\kunal\AppData\Local\Temp\ipykernel_32764\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [58]:
arr=np.arange(0,10)
arr*arr


array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [59]:
1/arr

C:\Users\kunal\AppData\Local\Temp\ipykernel_32764\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [61]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [62]:
np.log(arr)

C:\Users\kunal\AppData\Local\Temp\ipykernel_32764\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [63]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [64]:
arr.sum()


45

In [65]:
arr.mean()

4.5

In [66]:
arr.max()


9

In [67]:
arr.std()

2.8722813232690143

In [68]:
arr.var()

8.25

In [69]:
np.arange(0,25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [70]:
arr_2d=np.arange(0,25).reshape(5,5)

In [71]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [74]:
arr_2d.sum(axis=0 )#  sum across the rows

array([50, 55, 60, 65, 70])

In [75]:
arr_2d.sum(axis=1 )#  sum across the cols

array([ 10,  35,  60,  85, 110])